# Generated by Django 5.0.1 on 2026-01-31 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='is_compliant',
            field=models.BooleanField(default=False, help_text='True if > 8 hours (480 mins)'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='total_work_minutes',
            field=models.IntegerField(default=0, help_text='Total minutes worked'),
        ),
        migrations.CreateModel(
            name='RawPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('punch_type', models.CharField(blank=True, help_text='IN, OUT, or raw code', max_length=10)),
                ('attendance_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_punches', to='payroll.attendancelog')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
