# Generated by Django 5.0.1 on 2026-02-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_attendancelog_is_compliant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='entry_type',
            field=models.CharField(choices=[('AUTO', 'Auto Punch'), ('MANUAL', 'Manual Entry')], default='AUTO', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='remarks',
            field=models.TextField(blank=True, help_text='Reason for manual entry or adjustments', null=True),
        ),
    ]
