# Generated by Django 5.0.1 on 2026-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_attendancelog_entry_type_attendancelog_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollbatch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('VOID', 'Void')], default='DRAFT', max_length=20),
        ),
    ]
