# Generated by Django 5.0.1 on 2026-02-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_payrollbatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('WeeklyOff', 'Weekly Off'), ('Holiday', 'Holiday'), ('HalfDay', 'Half Day'), ('DISPUTED', 'Disputed'), ('VOID', 'Void')], default='Present', max_length=20),
        ),
    ]
