# Generated by Django 5.0.1 on 2026-02-10 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_attendancelog_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_statutory', models.BooleanField(default=False, help_text='If true, cannot be waived')),
                ('is_recurring', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='approved_overtime_minutes',
            field=models.IntegerField(default=0, help_text='Manager approved OT minutes'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If true, attendance cannot be modified by sync/manual edits'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='approved_ot_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='base_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pro-rated Basic + Allowances', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='ot_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='total_absent_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='total_full_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='total_half_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='variable_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commissions, Bonuses', max_digits=10),
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, help_text='If > 0, calculated as % of Basic', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.deductioncomponent')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_deductions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_waived', models.BooleanField(default=False)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.deductioncomponent')),
                ('payroll_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_deductions', to='payroll.payrollentry')),
            ],
        ),
    ]
