# Generated by Django 5.0.1 on 2026-02-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_deductioncomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='actual_work_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total worked hours for the month', max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='approved_ot_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Approved OT Hours for display', max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='lop_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Loss of Pay Amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='required_work_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total required hours for the month', max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='shortfall_work_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shortfall hours (basis for LOP)', max_digits=6),
        ),
    ]
