# Generated by Django 5.0.1 on 2026-03-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_manualpunchrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='is_absent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='If true, attendance cannot be modified by sync/manual edits'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='total_work_minutes',
            field=models.IntegerField(db_index=True, default=0, help_text='Total minutes worked'),
        ),
    ]
