# Generated by Django 5.0.1 on 2026-03-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_alter_attendancelog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('WeeklyOff', 'Weekly Off'), ('Holiday', 'Holiday'), ('HalfDay', 'Half Day'), ('DISPUTED', 'Disputed'), ('VOID', 'Void')], db_index=True, default='Present', max_length=20),
        ),
    ]
