# Generated by Django 5.0.1 on 2026-03-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_alter_attendancelog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpunch',
            name='punch_type',
            field=models.CharField(blank=True, db_index=True, help_text='IN, OUT, or raw code', max_length=10),
        ),
        migrations.AlterField(
            model_name='rawpunch',
            name='time',
            field=models.TimeField(db_index=True),
        ),
    ]
