# Generated by Django 5.0.1 on 2026-03-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_alter_rawpunch_punch_type_alter_rawpunch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollbatch',
            name='month',
            field=models.DateField(db_index=True, help_text='First day of the month for this payroll'),
        ),
        migrations.AlterField(
            model_name='payrollbatch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
