# Generated by Django 5.0.1 on 2026-01-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('EID', 'Emirates ID'), ('PSP', 'Passport'), ('VISA', 'Visa'), ('CNT', 'Labor Contract'), ('OTH', 'Other')], max_length=10)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('EXPIRED', 'Expired'), ('RENEWAL', 'Renewal in Progress'), ('ARCHIVED', 'Archived')], default='VALID', max_length=20)),
                ('file', models.FileField(upload_to='secure_docs/%Y/%m/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notification_sent_at', models.DateTimeField(blank=True, help_text='When the last expiry alert was triggered', null=True)),
            ],
        ),
    ]
