# Generated by Django 5.0.1 on 2026-02-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentvault',
            name='document_type',
            field=models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('DEGREE', 'Highest Qualification Degree/Certificate'), ('MARKSHEET', 'Final Semester Marksheet'), ('RELIEVING', 'Relieving Letter'), ('PAYSLIPS', "Last 3 Months' Payslips"), ('FORM16', 'Form 16 / Digital Tax Summary'), ('BANK_PROOF', 'Cancelled Cheque / Bank Passbook'), ('EPF_FORM', 'EPF Form 11'), ('OTHER', 'Other Documents')], max_length=10),
        ),
    ]
