# Generated by Django 5.0.1 on 2026-02-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_documentvault_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentvault',
            name='document_type',
            field=models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport'), ('DEGREE', 'Degree Certificate'), ('BANK_PROOF', 'Bank Passbook')], max_length=10),
        ),
    ]
