# Generated by Django 5.0.1 on 2026-01-30 06:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('HR_MANAGER', 'HR Manager'), ('CEO', 'CEO'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('SALES', 'Sales & Marketing'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('ADMIN', 'Administration')], default='IT', max_length=100)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(choices=[('GM', 'General Manager'), ('MGR', 'Manager'), ('HR_EXEC', 'HR Executive'), ('ACC', 'Accountant'), ('SR_DEV', 'Senior Developer'), ('JR_DEV', 'Junior Developer'), ('SALES_EXEC', 'Sales Executive'), ('OFFICE_ASST', 'Office Assistant'), ('DRIVER', 'Driver')], default='JR_DEV', max_length=100)),
                ('salary_basic', models.DecimalField(decimal_places=2, default=0.0, help_text='Basic Salary in AED', max_digits=10)),
                ('salary_allowance', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Allowances in AED', max_digits=10)),
                ('contract_type', models.CharField(choices=[('LIMITED', 'Limited Contract'), ('UNLIMITED', 'Unlimited Contract')], default='LIMITED', max_length=20)),
                ('mol_number', models.CharField(blank=True, help_text='Labor Card Number (14 Digits)', max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'Must be exactly 14 digits')])),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('_emirates_id', models.CharField(blank=True, db_column='emirates_id', help_text='Encrypted Emirates ID', max_length=255, null=True)),
                ('_passport_number', models.CharField(blank=True, db_column='passport_number', help_text='Encrypted Passport Number', max_length=255, null=True)),
                ('_iban', models.CharField(blank=True, db_column='iban', help_text='Encrypted IBAN', max_length=255, null=True)),
                ('bank_routing_code', models.CharField(blank=True, help_text='WPS Routing Code', max_length=9, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
