# Generated by Django 5.0.1 on 2026-02-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR_MANAGER', 'HR Manager'), ('CEO', 'CEO'), ('PROJECT_MANAGER', 'Project Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=50),
        ),
    ]
