# Generated by Django 5.0.1 on 2026-02-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('HR_MANAGER', 'HR Manager'), ('CEO', 'CEO'), ('PROJECT_MANAGER', 'Project Manager'), ('EMPLOYEE', 'Employee')], help_text='Optional secondary role', max_length=50, null=True),
        ),
    ]
