# Generated by Django 5.0.1 on 2026-02-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='salary_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total Allowances in INR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='salary_basic',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Basic Salary in INR', max_digits=10),
        ),
    ]
