# Generated by Django 5.0.1 on 2026-02-04 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_salary_allowance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='_emirates_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bank_routing_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mol_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='_pan_number',
            field=models.CharField(blank=True, db_column='pan_number', help_text='Encrypted PAN Card Number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='Aadhaar Card Number (12 Digits)', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Must be exactly 12 digits')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='Bank IFSC Code (11 Characters)', max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Invalid IFSC format (e.g., HDFC0001234)')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='_iban',
            field=models.CharField(blank=True, db_column='iban', help_text='Encrypted Account Number / IBAN', max_length=255, null=True),
        ),
    ]
