# Generated by Django 5.0.1 on 2026-02-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser__emirates_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('FRONTEND', 'Frontend Developer'), ('BACKEND', 'Backend Developer'), ('DESIGN', 'Design')], default='BACKEND', max_length=100),
        ),
    ]
