# Generated by Django 5.0.1 on 2026-02-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Company-assigned Employee Code', max_length=50, null=True, unique=True),
        ),
    ]
