# Generated by Django 5.0.1 on 2026-02-06 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='manager',
        ),
        migrations.AddField(
            model_name='customuser',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Managers assigned to this employee', related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
