# Generated by Django 5.0.1 on 2026-02-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_manager_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('FRONTEND', 'Frontend Developer'), ('BACKEND', 'Backend Developer'), ('DESIGNER', 'Designer'), ('PROJECT_MANAGER', 'Project Manager'), ('QC', 'QC')], default='BACKEND', max_length=100),
        ),
    ]
