# Generated by Django 5.0.1 on 2026-02-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, choices=[('FRONTEND', 'Frontend Developer'), ('BACKEND', 'Backend Developer'), ('DESIGNER', 'Designer'), ('PROJECT_MANAGER', 'Project Manager'), ('QC', 'QC (Quality Control)')], default=None, max_length=100, null=True),
        ),
    ]
