# Generated by Django 5.0.1 on 2026-02-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_designation_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, choices=[('FRONTEND', 'Frontend Developer'), ('BACKEND', 'Backend Developer'), ('DESIGNER', 'Designer'), ('PROJECT_MANAGER', 'Project Manager'), ('QC', 'QC (Quality Control)'), ('HR_EXECUTIVE', 'HR Executive'), ('HR_MANAGER', 'HR Manager'), ('RECRUITER', 'Recruiter'), ('PAYROLL_SPEC', 'Payroll Specialist'), ('SALES_EXEC', 'Sales Executive'), ('SALES_MANAGER', 'Sales Manager'), ('MARKETING_EXEC', 'Marketing Executive'), ('BIZ_DEV', 'Business Development'), ('ACCOUNTANT', 'Accountant'), ('FINANCE_MANAGER', 'Finance Manager'), ('AUDITOR', 'Auditor'), ('OPS_EXECUTIVE', 'Operations Executive'), ('OPS_MANAGER', 'Operations Manager'), ('LOGISTICS_COORD', 'Logistics Coordinator'), ('ADMIN_EXECUTIVE', 'Admin Executive'), ('OFFICE_MANAGER', 'Office Manager'), ('RECEPTIONIST', 'Receptionist')], default=None, max_length=100, null=True),
        ),
    ]
