# Generated by Django 5.0.1 on 2026-03-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_expand_designation_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='additional_role',
            field=models.CharField(blank=True, help_text='Optional secondary role', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='Employee', max_length=50),
        ),
    ]
