# Generated by Django 5.0.1 on 2026-03-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_additional_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='additional_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('HR_MANAGER', 'HR Manager'), ('CEO', 'CEO'), ('PROJECT_MANAGER', 'Project Manager'), ('EMPLOYEE', 'Employee')], help_text='Optional secondary role', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR_MANAGER', 'HR Manager'), ('CEO', 'CEO'), ('PROJECT_MANAGER', 'Project Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=50),
        ),
    ]
