# Generated by Django 5.0.1 on 2026-02-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
