# Generated by Django 5.0.1 on 2026-02-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code',
        ),
    ]
