# Generated by Django 5.0.1 on 2026-01-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('total_entitlement', models.FloatField(default=30.0)),
                ('days_used', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Manager'), ('GR_APPROVED', 'Manager Approved'), ('HR_PROCESSED', 'HR Processed'), ('APPROVED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('manager_comment', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('days_entitlement', models.IntegerField(default=30, help_text='Annual entitlement days')),
                ('is_paid', models.BooleanField(default=True)),
                ('is_carry_forward', models.BooleanField(default=False)),
                ('encashable', models.BooleanField(default=False, help_text='Can be encashed at EOS')),
                ('accrual_frequency', models.CharField(choices=[('ANNUAL', 'Annual (Upfront)'), ('MONTHLY', 'Monthly (Pro-rata)')], default='ANNUAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(help_text='Home Country Airport', max_length=100)),
                ('travel_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('benefit_type', models.CharField(choices=[('TICKET', 'Flight Ticket'), ('CASH', 'Cash Encashment')], default='TICKET', max_length=10)),
                ('is_encashment', models.BooleanField(default=False, help_text='Deprecated: Use benefit_type')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cost or Cash value', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('MGR_APPROVED', 'Manager Approved'), ('HR_PROCESSED', 'HR Processed'), ('BOOKED', 'Booked'), ('ENCASHED', 'Encashed'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
