# Generated by Django 5.0.1 on 2026-02-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='eligibility_gender',
            field=models.CharField(choices=[('ALL', 'All Employees'), ('Male', 'Male Only'), ('Female', 'Female Only')], default='ALL', help_text='Who is eligible for this leave?', max_length=10),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='min_service_days',
            field=models.IntegerField(default=0, help_text='Minimum days of service required to apply'),
        ),
    ]
