# Generated by Django 5.0.1 on 2026-02-03 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leavetype_eligibility_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROJECT_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Manager'), ('MGR_APPROVED', 'Manager Approved'), ('HR_PROCESSED', 'HR Processed'), ('APPROVED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
