# Generated by Django 5.0.1 on 2026-02-03 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leaverequest_assigned_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['PROJECT_MANAGER', 'CEO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
