# Generated by Django 5.0.1 on 2026-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_alter_leaverequest_assigned_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text="Fixed duration in days. Set to 1 for 'Normal Day', 30 for 'Annual', or Leave Empty for Manual.", null=True),
        ),
    ]
