# Generated by Django 5.0.1 on 2026-02-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_leavetype_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='reset_monthly',
            field=models.BooleanField(default=False, help_text='If checked, the leave balance resets every month (Non-cumulative)'),
        ),
    ]
