# Generated by Django 5.0.1 on 2026-02-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_leavetype_reset_monthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='allow_unlimited',
            field=models.BooleanField(default=False, help_text='Skip entitlement / balance check (e.g. for Unpaid/Emergency Leave).'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='hidden_unless_used',
            field=models.BooleanField(default=False, help_text='Hide from dashboard unless the user has used it.'),
        ),
    ]
