# Generated by Django 5.0.1 on 2026-02-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_leavetype_allow_unlimited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_session',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_half_day',
            field=models.BooleanField(default=False, help_text='Allow half-day requests for this leave type.'),
        ),
    ]
