# Generated by Django 5.0.1 on 2026-02-16 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0010_configure_half_day_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='Medical certificate or supporting document.', null=True, upload_to='leave_documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='document_status',
            field=models.CharField(choices=[('NONE', 'Not Required'), ('PENDING', 'Pending Upload'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Classification'), ('PAID', 'Paid Leave'), ('LOP', 'Loss of Pay')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_document',
            field=models.BooleanField(default=False, help_text='If checked, requires document upload after manager approval (e.g. Sick Leave).'),
        ),
    ]
