# Generated by Django 5.0.1 on 2026-03-09 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_leaverequest_attachment_leaverequest_document_status_and_more'),
        ('payroll', '0013_alter_payrollbatch_month_alter_payrollbatch_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LOPAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_lop_days', models.FloatField(help_text='X days of LOP')),
                ('requested_annual_leave_days', models.FloatField(help_text='Y days of Annual Leave used')),
                ('remaining_lop_days', models.FloatField(help_text='(X - Y) days of LOP remaining')),
                ('converted_hours', models.DecimalField(decimal_places=2, help_text='Hours deducted from shortfall', max_digits=10)),
                ('reason', models.TextField(help_text='Reason for the waive/conversion')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_lop_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lop_adjustments', to=settings.AUTH_USER_MODEL)),
                ('payroll_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lop_adjustments', to='payroll.payrollentry')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_lop_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LOP Adjustment',
                'verbose_name_plural': 'LOP Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
