# Generated by Django 5.0.1 on 2026-03-09 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0012_lopadjustment'),
        ('payroll', '0013_alter_payrollbatch_month_alter_payrollbatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lopadjustment',
            name='payroll_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lop_adjustments', to='payroll.payrollentry'),
        ),
    ]
