# Generated by Django 5.0.1 on 2026-01-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nexteons', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, help_text='Used in email footers')),
                ('trn_number', models.CharField(blank=True, help_text='Tax Registration Number', max_length=50, verbose_name='TRN / Tax ID')),
                ('employer_id', models.CharField(blank=True, help_text='Required for SIF File generation', max_length=50, verbose_name='WPS Employer ID')),
                ('wps_agent_id', models.CharField(default='000000000', help_text='Bank/Exchange Routing Code (9 digits) for SIF Header', max_length=9)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
    ]
