# Generated by Django 5.0.1 on 2026-02-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False, help_text='Repeats every year?')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='companysettings',
            name='work_friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='work_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='work_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='work_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='work_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='work_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='work_wednesday',
            field=models.BooleanField(default=True),
        ),
    ]
