# Generated by Django 5.0.1 on 2026-02-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_timesta_189a84_idx',
            old_name='core_auditl_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_id_2a1528_idx',
            old_name='core_auditl_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_f07419_idx',
            old_name='core_auditl_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_module_8dce1c_idx',
            old_name='core_auditl_module_idx',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='employer_id',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='trn_number',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='wps_agent_id',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='gstin',
            field=models.CharField(blank=True, help_text='GST Identification Number', max_length=50, verbose_name='GSTIN'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Permanent Account Number', max_length=50, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='tan_number',
            field=models.CharField(blank=True, help_text='Tax Deduction Account Number', max_length=50, verbose_name='TAN Number'),
        ),
    ]
