# Generated by Django 5.0.1 on 2026-02-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_core_auditl_timesta_idx_core_auditl_timesta_189a84_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='currency_code',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=10),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='second_saturday_holiday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='work_saturday',
            field=models.BooleanField(default=True),
        ),
    ]
