# Generated by Django 5.0.1 on 2026-02-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companysettings_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='employee_id_prefix',
            field=models.CharField(default='EMP-', help_text='Default prefix for new employees (e.g. EMP-)', max_length=10),
        ),
    ]
