# Generated by Django 5.0.1 on 2026-02-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_companysettings_employee_id_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPORT', 'Exported'), ('IMPORT', 'Imported'), ('VIEW', 'Viewed')], max_length=20),
        ),
    ]
