# Generated by Django 4.2.27 on 2026-02-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('PAYROLL', 'Payroll'), ('ATTENDANCE', 'Attendance'), ('LEAVES', 'Leaves'), ('EMPLOYEES', 'Employees'), ('USERS', 'Users'), ('DOCUMENTS', 'Documents'), ('TICKETS', 'Air Tickets'), ('MEETINGS', 'Meetings'), ('SYSTEM', 'System'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
